# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Folake Knudsen 
email: folake.knudsen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of visual designer, Folake Knudsen
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://folakeknudsen.com" # the base hostname & protocol for your site
twitter_username: folakeknudsen
github_username:  fosibodu

# Build settings
markdown: kramdown
